#pragma once

#undef PRODUCT
#define PRODUCT "HPD v2 (display/trackball)"

#define VIAL_KEYBOARD_UID {0x74, 0x2A, 0xFA, 0x6B, 0xEB, 0x6E, 0x5B, 0x17}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

#define MATRIX_COLS 7
#define MATRIX_ROWS 12

#define SPI_DRIVER SPID1
#define SPI_SCK_PIN GP10
#define SPI_MOSI_PIN GP11
#define SPI_MISO_PIN GP8

// LCD config
#define LCD_DC_PIN GP26
#define LCD_CS_PIN GP9
#define LCD_RST_PIN GP8
#define QUANTUM_PAINTER_LVGL_USE_CUSTOM_CONF
#define QUANTUM_PAINTER_DISPLAY_TIMEOUT 0
#define QUANTUM_PAINTER_TASK_THROTTLE 50
#define BACKLIGHT_PWM_CHANNEL RP2040_PWM_CHANNEL_B
#define BACKLIGHT_PWM_DRIVER PWMD5
#define BACKLIGHT_LEVELS 10
#define BACKLIGHT_PIN GP27
#define QP_ROTATION QP_ROTATION_0

#define SPLIT_TRANSACTION_IDS_USER RPC_SYNC_TOUCH, RPC_SYNC_DISPLAY, RPC_SYNC_HID
#define SPLIT_LAYER_STATE_ENABLE
#define SPLIT_MODS_ENABLE
#define SPLIT_ACTIVITY_ENABLE

#define PMW33XX_CS_PIN GP9
#define SPLIT_POINTING_ENABLE
#define POINTING_DEVICE_RIGHT
#define POINTING_DEVICE_TASK_THROTTLE_MS 10
#define POINTING_DEVICE_INVERT_X

#define VIA_EEPROM_LAYOUT_OPTIONS_SIZE 2
#define VIA_EEPROM_LAYOUT_OPTIONS_DEFAULT 0x0000035d

#define POINTING_DEVICE_AUTO_MOUSE_ENABLE
#define AUTO_MOUSE_DEFAULT_LAYER 4

#define EH_POINTING_KEYCODES

#define EH_SHORT_PRODUCT_NAME "HPDv2"
#define EH_HAS_DISPLAY
