#pragma once

#define VIAL_KEYBOARD_UID {0x5D, 0x0D, 0xDD, 0xD9, 0xED, 0xD3, 0x45, 0x17}
#define VIAL_UNLOCK_COMBO_ROWS { 1, 1 }
#define VIAL_UNLOCK_COMBO_COLS { 4, 3 }

#define EH_PROCESS_RECORD_USER_FIRST

#define VIAL_COMBO_ENTRIES 72