#pragma once

#define VIAL_KEYBOARD_UID {0x74, 0x2A, 0xFA, 0x6B, 0xEB, 0x6E, 0x5B, 0x17}
#define VIAL_UNLOCK_COMBO_ROWS { 0, 0 }
#define VIAL_UNLOCK_COMBO_COLS { 0, 1 }

#define ENCODERS_PAD_A_RIGHT { GP8 }
#define ENCODERS_PAD_B_RIGHT { GP9 }
#define ENCODER_RESOLUTION 4
#define ENCODER_DEFAULT_POS 0x3
#define ENCODERS_PAD_A { GP8 }
#define ENCODERS_PAD_B { GP9 }

#define MATRIX_COLS 7
#define MATRIX_ROWS 12

#undef MATRIX_COL_PINS
#undef MATRIX_ROW_PINS
#define MATRIX_COL_PINS_RIGHT { GP7, GP12, GP13, GP14, GP15, GP28, GP10 }
#define MATRIX_ROW_PINS_RIGHT { GP6, GP5, GP4, GP3, GP2, GP11 }
#define MATRIX_COL_PINS { GP7, GP12, GP13, GP14, GP15, GP28, GP10 }
#define MATRIX_ROW_PINS { GP6, GP5, GP4, GP3, GP2, GP11 }

#define WS2812_DI_PIN GP26
#define RGBLIGHT_LED_COUNT 2
#define RGBLED_SPLIT {1, 1}
#define RGBLIGHT_SLEEP
#define RGBLIGHT_SPLIT
#define RGBLIGHT_LAYERS
#define RGBLIGHT_MAX_LAYERS 16
#define RGBLIGHT_LAYERS_RETAIN_VAL
#define RGBLIGHT_DEFAULT_VAL 50
#define RGBLIGHT_LIMIT_VAL 150
#define RGBLIGHT_DEFAULT_SAT 0

#undef PRODUCT
#define PRODUCT "HPD v2 enc/enc"
